[project]
authors = [
  {name = "Ash Vardanian", email = "1983160+ashvardanian@users.noreply.github.com"},
]
dependencies = [
  # Core
  "pytest",
  "pytest-benchmark>=5.2.3", # Numerics
  "numba",
  "numpy", # Composite structures and type checking
  "attrs",
  "pydantic", # Heterogeneous data structures
  "pandas",
  "pyarrow", # Networking
  "fastapi", # HTTP server
  "httpx", # Alternative HTTP client
  "requests", # HTTP client
  "uvicorn", # Underlying ASGI server
]
description = "Microbenchmarks for a performance-first mindset in Python"
license = {file = "LICENSE"}
name = "less_slow"
readme = "README.md"
requires-python = ">=3.10"
version = "0.5.2"

[project.urls]
"For C++" = "https://github.com/ashvardanian/less_slow.cpp"
"For Rust" = "https://github.com/ashvardanian/less_slow.rs"
Homepage = "https://github.com/ashvardanian/less_slow.py"
Issues = "https://github.com/ashvardanian/less_slow.py/issues"
Repository = "https://github.com/ashvardanian/less_slow.py"

[tool.pytest.ini_options]
addopts = "-ra -q"
minversion = "6.0"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]
